<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NoniPilot.ComputerControl\NoniPilot.ComputerControl.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.47.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
